### PR TITLE
fix: prevent text selection

### PR DESCRIPTION
**Pull request by nikrb**

### CODE REVIEW

**Comment by Mortuie** [comment]
Why are we doing this ?

**Comment by nikrb** [comment]
to prevent (accidental) selection of text - I think it looks unprofessional

**Comment by Mortuie** [comment]
Still don't quite understand, can I see a screenshot to show difference ?

**Comment by nikrb** [comment]
really? you must be exceedingly deft with a mouse ;)
so ... click anywhere on the white part of a web page (ours or this github page), then drag up or down holding down the mouse ... you'll see the text highlighted.

**Comment by Mortuie** [comment]
OHHHHHH and you've turned that off ?

**Comment by nikrb** [comment]
yes I have turned it off :)

**Pull request merged**
